# Generated by Django 4.2.7 on 2024-01-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemcontroller', '0002_rating_user_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
