# Generated by Django 4.2.7 on 2024-01-09 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Name', models.CharField(max_length=100)),
                ('Book_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Book_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('Book_Brand_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='brand.brand')),
            ],
        ),
    ]
