# Generated by Django 4.2.7 on 2023-12-29 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_Name', models.CharField(max_length=100)),
                ('Car_Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Car_Brand_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Brand', to='brand.brand')),
            ],
        ),
    ]
