# Generated by Django 4.2.7 on 2023-12-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
