# Generated by Django 4.2.7 on 2023-12-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_car_car_img_alter_car_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
