# Generated by Django 4.2.7 on 2023-12-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_mymodel3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel3',
            name='boolean_field',
        ),
        migrations.RemoveField(
            model_name='mymodel3',
            name='char_field',
        ),
        migrations.RemoveField(
            model_name='mymodel3',
            name='date_field',
        ),
        migrations.RemoveField(
            model_name='mymodel3',
            name='date_time_field',
        ),
        migrations.AddField(
            model_name='mymodel3',
            name='decimal_field',
            field=models.DecimalField(decimal_places=2, default=9, max_digits=5),
        ),
    ]
