# Generated by Django 4.2.7 on 2023-12-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_remove_mymodel3_boolean_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel3',
            name='email_field',
            field=models.EmailField(default='saka@gmail.com', max_length=254),
        ),
    ]
