# Generated by Django 4.2.7 on 2023-12-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_mymodel3_email_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_field', models.DurationField()),
            ],
        ),
    ]
