# Generated by Django 4.2.7 on 2023-12-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_mymodel4'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_field', models.FileField(upload_to='files/')),
            ],
        ),
    ]
