# Generated by Django 4.2.7 on 2023-12-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_mymodel5'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_field', models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='mymodel5',
            name='file_field',
            field=models.FileField(upload_to='download (2).jpg'),
        ),
    ]
