# Generated by Django 4.2.7 on 2023-12-17 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_mymodel6_alter_mymodel5_file_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel1',
        ),
        migrations.DeleteModel(
            name='MyModel3',
        ),
        migrations.DeleteModel(
            name='MyModel4',
        ),
        migrations.DeleteModel(
            name='MyModel5',
        ),
        migrations.DeleteModel(
            name='MyModel6',
        ),
    ]
