<<<<<<< HEAD
# Generated by Django 4.2.7 on 2023-12-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormsAPI', '0002_mymodule1_mymodule2'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodule2',
            name='decimal_field',
            field=models.DecimalField(decimal_places=5, default=5, max_digits=5),
        ),
    ]
=======
# Generated by Django 4.2.7 on 2023-12-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormsAPI', '0002_mymodule1_mymodule2'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodule2',
            name='decimal_field',
            field=models.DecimalField(decimal_places=5, default=5, max_digits=5),
        ),
    ]
>>>>>>> 1536a79ed4bb132d457adca7cd486953d8e04534
