# Generated by Django 4.2.7 on 2023-12-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormsAPI', '0005_remove_mymodule2_decimal_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodule2',
            name='boolean_field',
        ),
        migrations.RemoveField(
            model_name='mymodule2',
            name='char_field',
        ),
        migrations.RemoveField(
            model_name='mymodule2',
            name='date_field',
        ),
        migrations.RemoveField(
            model_name='mymodule2',
            name='date_time_field',
        ),
        migrations.RemoveField(
            model_name='mymodule2',
            name='duration_field',
        ),
        migrations.RemoveField(
            model_name='mymodule2',
            name='email_field',
        ),
        migrations.RemoveField(
            model_name='mymodule2',
            name='file_field',
        ),
        migrations.RemoveField(
            model_name='mymodule2',
            name='file_path_field',
        ),
        migrations.RemoveField(
            model_name='mymodule2',
            name='float_field',
        ),
        migrations.RemoveField(
            model_name='mymodule2',
            name='generic_ip_address_field',
        ),
        migrations.RemoveField(
            model_name='mymodule2',
            name='integer_field',
        ),
        migrations.RemoveField(
            model_name='mymodule2',
            name='many_to_many_field',
        ),
        migrations.RemoveField(
            model_name='mymodule2',
            name='positive_big_integer_field',
        ),
        migrations.RemoveField(
            model_name='mymodule2',
            name='positive_small_integer_field',
        ),
        migrations.RemoveField(
            model_name='mymodule2',
            name='small_integer_field',
        ),
        migrations.RemoveField(
            model_name='mymodule2',
            name='text_field',
        ),
        migrations.RemoveField(
            model_name='mymodule2',
            name='time_field',
        ),
        migrations.RemoveField(
            model_name='mymodule2',
            name='url_field',
        ),
        migrations.RemoveField(
            model_name='mymodule2',
            name='uuid_field',
        ),
        migrations.AddField(
            model_name='mymodule2',
            name='name',
            field=models.CharField(default='sakib', max_length=20),
        ),
    ]
